/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.*;
import java.time.*;

/**
 *
 * @author Yahia
 */
public class ReturnBook extends javax.swing.JFrame {
    
    
    public boolean isInteger( String input ) { 
    try { 
        Integer.parseInt( input ); 
        return true; 
    } 
    catch( Exception e ) {  
        return false;
    } 
    }
    

    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        bookCallNoTextField = new javax.swing.JTextField();
        studentIdField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Student ID:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Return Book");

        jLabel2.setText("Book Call No:");

        returnButton.setText("Return");
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(104, 104, 104)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookCallNoTextField)
                            .addComponent(studentIdField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(bookCallNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(returnButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed


            IssuedBookFileReader irdr = new IssuedBookFileReader();
            IssuedBookFileReader.IssuedBookList.clear();
            irdr.readBooks();
            
            BookFileReader brdr = new BookFileReader();
            BookFileReader.BookList.clear();
            brdr.readBooks();
            
            BookFileWriter brtr = new BookFileWriter();
            IssueBookFileWriter irtr = new IssueBookFileWriter();
            if(studentIdField.getText().equals("") || bookCallNoTextField.getText().equals("")){
               JOptionPane.showMessageDialog(null,"Please fill all the fields !" ,"Message",JOptionPane.INFORMATION_MESSAGE); 
               return;
            }
            if(!isInteger(studentIdField.getText())){
                JOptionPane.showMessageDialog(null,"Student id must be a number !" ,"Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }    
            int i,j;
            for(i=0;i<IssuedBookFileReader.IssuedBookList.size();i++){
                if(IssuedBookFileReader.IssuedBookList.get(i).getBookCallNo().equals(bookCallNoTextField.getText()) 
                        && IssuedBookFileReader.IssuedBookList.get(i).getStudentId() == Integer.parseInt(studentIdField.getText())){
                    for(j=0;j<BookFileReader.BookList.size();j++){
                        if(IssuedBookFileReader.IssuedBookList.get(i).getBookCallNo().equals(BookFileReader.BookList.get(j).getCallNo()) ){
                            
                            
                         //  Format f = new SimpleDateFormat("dd/MM/yyyy");
                         //  String idate= f.format(IssuedBookFileReader.IssuedBookList.get(i).getIssueDate());
                            LocalDate cDate = LocalDate.now();
                            ZonedDateTime zdt = cDate.atStartOfDay(ZoneId.systemDefault());
                            Instant instant = zdt.toInstant();
                             Date rDate = Date.from(instant);
                           
                           if(IssuedBookFileReader.IssuedBookList.get(i).getIssueDate().compareTo(rDate)<0){
                               
                              
                               BookFileReader.BookList.get(j).incQuantity(1);
                        IssuedBookFileReader.IssuedBookList.remove(i);
                        irtr.rewriteBooks();
                        brtr.rewriteBooks();
                        JOptionPane.showMessageDialog(null,"Book returned late !\nPenalty = 50 EGP" ,"Warning",JOptionPane.WARNING_MESSAGE);
                       // JOptionPane.showMessageDialog(null,"Book returned successfully !" ,"Message",JOptionPane.INFORMATION_MESSAGE);
                        return;
                               
                               
                           } 
                           else{   
                           
                        BookFileReader.BookList.get(j).incQuantity(1);
                        IssuedBookFileReader.IssuedBookList.remove(i);
                        irtr.rewriteBooks();
                        brtr.rewriteBooks();
                        JOptionPane.showMessageDialog(null,"Book returned successfully !" ,"Message",JOptionPane.INFORMATION_MESSAGE);
                        return;
                        
                    }
                    }
                    
                    
                       //IssuedBookFileReader.IssuedBookList.remove(i);

                    
                    
                }
                
                
            }
        
            if(i == IssuedBookFileReader.IssuedBookList.size())
               JOptionPane.showMessageDialog(null,"Book couldn't be found !" ,"Message",JOptionPane.INFORMATION_MESSAGE); 


        
        //JOptionPane.showMessageDialog(null,"Book returned successfully !" ,"Message",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_returnButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        LibrarianSection l = new LibrarianSection();
        l.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookCallNoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton returnButton;
    private javax.swing.JTextField studentIdField;
    // End of variables declaration//GEN-END:variables
}
