/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static librarysystem.StudentLogin.sid;

/**
 *
 * @author Yahia
 */
public class StudentPage extends javax.swing.JFrame {

    /**
     * Creates new form StudentPage
     */
    public StudentPage() {
        initComponents();
        addRowsToJTable();
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
     public void addRowsToJTable(){
    
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    StudentFileReader srdr = new StudentFileReader();
    StudentFileReader.StudentList.clear();
    srdr.readStudents();
    
    IssuedBookFileReader irdr = new IssuedBookFileReader();
    IssuedBookFileReader.IssuedBookList.clear();
    irdr.readBooks();
    
    ArrayList <String> str= new ArrayList <> ();// All books issued by this student
    
    
     int j;   
    for(int i=0;i<StudentFileReader.StudentList.size();i++){
   
    if(StudentFileReader.StudentList.get(i).getId() == (StudentLogin.sid))  { 
        for(j=0;j<IssuedBookFileReader.IssuedBookList.size();j++){
        
        if(IssuedBookFileReader.IssuedBookList.get(j).getStudentName().equals(StudentFileReader.StudentList.get(i).getName())
                && IssuedBookFileReader.IssuedBookList.get(j).getStudentId() == (StudentFileReader.StudentList.get(i).getId()) 
                && IssuedBookFileReader.IssuedBookList.get(j).getStudentContactNumber().equals(StudentFileReader.StudentList.get(i).getContactNumber())){
        
        str.add(IssuedBookFileReader.IssuedBookList.get(j).getBookCallNo());
            
        
        }
        
        
        
        
        }
        
        
        
     model.addRow(new Object[]{StudentFileReader.StudentList.get(i).getId(),StudentFileReader.StudentList.get(i).getName()
             ,StudentFileReader.StudentList.get(i).getPassword(),StudentFileReader.StudentList.get(i).getEmail()
             ,StudentFileReader.StudentList.get(i).getAddress(),StudentFileReader.StudentList.get(i).getCity(),StudentFileReader.StudentList.get(i).getContactNumber(),str.get(0)});
          //   System.out.println("sid:  "+sid + "  "+"ID:  "+StudentFileReader.StudentList.get(i).getId());
        //  model.addRow(new Object[]{"","","","","","","",str.get(0)});
            
       for(int k=1;k<str.size();k++){
       
           model.addRow(new Object[]{"","","","","","","",str.get(k)});
       
       }   
          
             
             break;
    }
    }
    
    
}
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Password", "Email", "Address", "City", "Contact No.", "Issued Books"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
